version: 2
sphinx:
  builder: html
  configuration: docs/conf.py

formats:
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt
